// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ant-picker': string;
  form: string;
  form__btnBlock: string;
  form__btnBlock_cancel: string;
  form__btnBlock_continue: string;
  form__cityState: string;
  form__heading: string;
  form__inputsBlock: string;
  form__inputsColumn: string;
  form__requiredFields: string;
  form__subtitle: string;
}
export const cssExports: CssExports;
export default cssExports;
